In [1]:
*from sklearn.metrics.cluster import homogeneity_score
homogeneity_score([0, 0, 1, 1], [1, 1, 0, 0])

1.0

In [6]:
homogeneity_score([0, 0, 1, 1], [3, 0, 0, 2])

0.49999999999999994

In [7]:
homogeneity_score([0, 0, 1, 1], [1, 2, 2, 2])

0.31127812445913283

In [8]:
from sklearn.metrics.cluster import completeness_score
completeness_score([0, 0, 1, 1], [1, 1, 0, 0])

1.0

In [10]:
completeness_score([0, 0, 1, 1], [1, 1, 2, 3])

0.6666666666666666

In [41]:
a=[1,1,2,2,3,3,1,2,3,1]
b=[1,2,3,3,4,5,2,3,4,3]

In [18]:
completeness_score(a,b)

0.7213688125736629

In [42]:
homogeneity_score(a,b)

0.7934300092382586

In [20]:
from sklearn.metrics import f1_score
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
f1_score(y_true, y_pred, average='macro') 

0.26666666666666666

In [43]:
f1_score(a, b, average='macro') 

ValueError: Target is multiclass but average='binary'. Please choose another average setting.

In [47]:
from sklearn.metrics import accuracy_score
a=[0, 0, 1, 1] 
b=[1, 1, 0, 0]
print(accuracy_score(a,b))
homogeneity_score(a,b)

0.0


1.0

In [54]:
a=[0, 0, 1, 1,0,0]
b=[0,1,2,3,0,2]
print(accuracy_score(a,b))
homogeneity_score(a,b)

0.3333333333333333


0.6370087710606406

In [55]:
a=[0,0,1,1,0,0]
b=[0,1,2,1,0,2]
print(accuracy_score(a,b))
homogeneity_score(a,b)

0.5


0.27401754212128104

In [ ]:
a=[0,0,1,1,0,0]
b=[0,1,2,3,0,2]
print(accuracy_score(a,b))
homogeneity_score(a,b)

In [ ]:
## Programa para encontraraccuracy en mas grupos que clusters reales

In [109]:
import numpy as np

a = np.array([0,0,1,1,2,2,0,1,2])
b = np.array([0,1,2,2,3,4,1,2,3])



In [110]:
a.max()
b.max()

4

In [116]:
c= np.arange(a.max()+1)
b1=np.arange(b.max()+1)
print(c)
print(b1)

[0 1 2]
[0 1 2 3 4]


In [136]:
v = []
for i in b1:
    v.append(np.where(b==i)[0])

In [137]:
v

[array([0]), array([1, 6]), array([2, 3, 7]), array([4, 8]), array([5])]

In [142]:
v[2]

array([2, 3, 7])

(array([5]),)